# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Load_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
"""
Ui_Dialog_QENSload class.

Filename: load_win_ui.py
Author: Beatriz Robles Hernández
Date: 2025-05-27
Version: 1.0
Description:
    This script creates the class of the GUI that uses
    the load_Dlg application.

License: GLP
Contact: broblesher@gmail.com
Dependencies: os, PyQt5
"""
# Import statements
import os
from PyQt5 import QtCore, QtWidgets  # QtGui,


class Ui_Dialog_QENSload(object):
    def setupUi(self, Dialog_QENSload):
        Dialog_QENSload.setObjectName("Dialog_QENSload")
        Dialog_QENSload.resize(450, 150)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            Dialog_QENSload.sizePolicy().hasHeightForWidth())
        Dialog_QENSload.setSizePolicy(sizePolicy)
        Dialog_QENSload.setMaximumSize(QtCore.QSize(1000, 150))
        self.gridLayout = QtWidgets.QGridLayout(Dialog_QENSload)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.label_input = QtWidgets.QLabel(Dialog_QENSload)
        self.label_input.setObjectName("label_input")
        self.verticalLayout_1.addWidget(self.label_input)
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.lineEdit_iFile = QtWidgets.QLineEdit(Dialog_QENSload)
        self.lineEdit_iFile.setObjectName("lineEdit_iFile")
        self.horizontalLayout_1.addWidget(self.lineEdit_iFile)
        self.pushButton_iFile = QtWidgets.QPushButton(Dialog_QENSload)
        self.pushButton_iFile.setObjectName("pushButton_iFile")
        self.horizontalLayout_1.addWidget(self.pushButton_iFile)
        self.verticalLayout_1.addLayout(self.horizontalLayout_1)
        self.label_intrument = QtWidgets.QLabel(Dialog_QENSload)
        self.label_intrument.setObjectName("label_intrument")
        self.verticalLayout_1.addWidget(self.label_intrument)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_IN5 = QtWidgets.QRadioButton(Dialog_QENSload)
        self.radioButton_IN5.setChecked(False)
        self.radioButton_IN5.setObjectName("radioButton_IN5")
        self.horizontalLayout_4.addWidget(self.radioButton_IN5)
        self.radioButton_IN16B = QtWidgets.QRadioButton(Dialog_QENSload)
        self.radioButton_IN16B.setChecked(False)
        self.radioButton_IN16B.setObjectName("radioButton_IN16B")
        self.horizontalLayout_4.addWidget(self.radioButton_IN16B)
        self.radioButton_FOCUS = QtWidgets.QRadioButton(Dialog_QENSload)
        self.radioButton_FOCUS.setChecked(False)
        self.radioButton_FOCUS.setObjectName("radioButton_FOCUS")
        self.horizontalLayout_4.addWidget(self.radioButton_FOCUS)
        self.radioButton_LET = QtWidgets.QRadioButton(Dialog_QENSload)
        self.radioButton_LET.setChecked(False)
        self.radioButton_LET.setObjectName("radioButton_LET")
        self.horizontalLayout_4.addWidget(self.radioButton_LET)
        self.verticalLayout_1.addLayout(self.horizontalLayout_4)
        self.pushButton_Load = QtWidgets.QPushButton(Dialog_QENSload)
        self.pushButton_Load.setObjectName("pushButton_Load")
        self.verticalLayout_1.addWidget(self.pushButton_Load)
        self.gridLayout.addLayout(self.verticalLayout_1, 0, 0, 1, 1)

        self.retranslateUi(Dialog_QENSload)
        self.pushButton_Load.clicked.connect(Dialog_QENSload.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog_QENSload)

    def retranslateUi(self, Dialog_QENSload):
        _translate = QtCore.QCoreApplication.translate
        Dialog_QENSload.setWindowTitle(
            _translate("Dialog_QENSload", "Load QENS data"))
        self.label_input.setText(
            _translate("Dialog_QENSload", "Input path and file name:"))
        self.lineEdit_iFile.setText(
            _translate("Dialog_QENSload", os.path.expanduser('~')))
        self.lineEdit_iFile.setText(
            _translate("Dialog_QENSload", "Input File"))
        self.pushButton_iFile.setText(_translate("Dialog_QENSload", "Browse"))
        self.label_intrument.setText(
            _translate("Dialog_QENSload", "Instrument:"))
        self.radioButton_IN5.setText(_translate("Dialog_QENSload", "IN5"))
        self.radioButton_IN16B.setText(_translate("Dialog_QENSload", "IN16B"))
        self.radioButton_FOCUS.setText(_translate("Dialog_QENSload", "FOCUS"))
        self.radioButton_LET.setText(_translate("Dialog_QENSload", "LET"))
        self.pushButton_Load.setText(_translate("Dialog_QENSload", "Load"))
